spring:
    application:
        name: persistence
    datasource:
        url: jdbc:p6spy:h2:mem:persistence;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    jpa:
        database: H2
